name: Manual Draft Post (Blogger)

on:
  workflow_dispatch: {}

jobs:
  run-draft:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY:        ${{ secrets.GEMINI_API_KEY }}
      BLOG_URL:              ${{ secrets.BLOG_URL }}
      CLIENT_ID:             ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET:         ${{ secrets.CLIENT_SECRET }}
      REFRESH_TOKEN:         ${{ secrets.REFRESH_TOKEN }}
      # مفاتيح الصور (اختياري)
      PEXELS_API_KEY:        ${{ secrets.PEXELS_API_KEY }}
      PIXABAY_API_KEY:       ${{ secrets.PIXABAY_API_KEY }}
      UNSPLASH_ACCESS_KEY:   ${{ secrets.UNSPLASH_ACCESS_KEY }}

      # إعدادات التشغيل
      PUBLISH_MODE:          draft
      RUN_ONCE:              "1"
      USE_EXTERNAL_CRON:     "0"
      TZ:                    Asia/Baghdad

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run main.py (draft)
        run: python main.py
